In [2]:
parent_path='../Data/New_Data_15-06-2020/'
%load_ext autoreload
%autoreload 2
import parmap
import pandas as pd
from tqdm import tqdm,tqdm_notebook
from utils.marking_similars import *
from utils.preprocess import *
from utils.emoji_extract import *
from utils.visualisation import latex_emoji_communities
import matplotlib.pyplot as plt
import empath
import seaborn as sns
from empath import Empath
import networkx as nx
import matplotlib
from numpy.random import seed
from numpy.random import randn
from scipy.stats import mannwhitneyu
emoji_stop=['☝','✌', '▪','🏼','🏻','🏿','🏾','🏽','➖','🔽','🇴','🇧','⚜','☘', '☕', '♦','▪','‼','♻','🇪','🇺','🇮', '🇳','🇲', '🇷', '🇸', '🇦', '🇵', '🇰', '🇨']

In [11]:
whatsapp_data=pd.read_csv(parent_path+'Data_text_spam_removed_v02_hi_en.csv')

In [ ]:

lexicon = Empath()
dict_map={0:'non fear speech',1:'fear speech'}

def get_empath_categories(df,normalize=False): 
    tuples=[]
    for index,row in tqdm(df.iterrows(),total=len(df)):
        dict_lexicon=lexicon.analyze(row['translated'], normalize=normalize)
        try:
            temp=dict_lexicon.values()
        except AttributeError:
            dict_lexicon=lexicon.analyze("sample text", normalize=normalize)
        temp=list(dict_lexicon.values())+[index,dict_map[row['one_fear_speech']]]
        tuples.append(temp)
    df_empath=pd.DataFrame(tuples,columns=list(dict_lexicon.keys())+['org_index','label'])
    
    
    print(len(df),len(df_empath))
    df=df.reset_index(drop=True)
    #df_with_empath=pd.concat([df,df_empath],axis=1)
    return df_empath


In [12]:
annotated_df=pd.read_pickle(parent_path+'Fearspeech_data_final.pkl')

In [ ]:
annotated_df_empath=get_empath_categories(annotated_df,normalize=True)
annotated_df_empath = pd.melt(annotated_df_empath,id_vars="label",var_name="category", value_name="normalized_value")
annotated_df_empath=annotated_df_empath[annotated_df_empath['category']!='org_index']
annotated_df_empath.head()
#categories=['help', 'cold', 'hate', 'cheerfulness', 'aggression', 'occupation', 'envy', 'family', 'crime', 'masculine', 'pride', 'dispute', 'government', 'weakness', 'horror', 'swearing_terms', 'leisure', 'suffering', 'royalty', 'wealthy', 'tourism', 'journalism', 'social_media', 'kill', 'ridicule', 'stealing', 'real_estate', 'home', 'divine', 'sexual', 'fear', 'irritability', 'religion', 'worship', 'leader', 'independence', 'movement', 'medieval', 'death', 'legend', 'heroic', 'celebration', 'violence', 'military', 'neglect', 'love', 'order', 'sympathy', 'anonymity', 'trust', 'ancient', 'deception', 'fight', 'dominant_personality', 'politeness', 'war', 'speaking', 'listen', 'disgust', 'fire', 'gain', 'injury', 'rage', 'work', 'valuable', 'warmth', 'youth', 'sadness', 'fun', 'emotional', 'joy', 'affection', 'ugliness', 'lust', 'shame', 'torment', 'anger', 'politics', 'strength', 'technology', 'breaking', 'power', 'animal', 'terrorism', 'disappointment', 'pain', 'philosophy', 'negotiate', 'negative_emotion', 'competing', 'law', 'friends', 'achievement', 'feminine', 'weapon', 'monster', 'giving', 'contentment', 'writing', 'positive_emotion']
categories=["hate", "crime", "aggression", "suffering", "kill", "home", "social_media", "divine", "leader", "death", "violence", "celebration", "order", "fight", "war", "speaking", "listen", "youth", "giving", "writing", "weapon", "negative_emotion", "pain", "power", "fun"]


matplotlib.rcParams['figure.figsize'] = (30,10)

sns.set(context='paper',style='white',font_scale=1.5)

temp=annotated_df_empath[annotated_df_empath['category'].isin(categories)]
font = {
    'weight' : 'normal',
    'size'   : 11}

sns.set(context='paper',style='white',font_scale=2.0)

g = sns.barplot(x="category", y="normalized_value",hue="label",data=temp)
#g=add_values(g,df_admin,15,order_list)
#plt.ylabel('number of groups as admin')
g.set_xticklabels(
        g.get_xticklabels(), 
        rotation=45, 
        horizontalalignment='right',
        fontweight='normal',
        fontsize='medium'

    )

xlist_label=[]

for cat in categories:
    temp=annotated_df_empath[annotated_df_empath['category']==cat]
    treatment=np.array(temp[temp['label']=='fear speech'].normalized_value)
    control=np.array(temp[temp['label']=='non fear speech'].normalized_value)
    seed(2)
    # generate two independent samples
    # compare samples
    stat, p = mannwhitneyu(treatment, control)
    
    if(p<=0.00001):
        cat=cat+" ****"
    elif(p<=0.0001):
        cat=cat+" ***"
    elif(p<=0.001):
        cat=cat+" **"
    elif(p<0.01):
        cat=cat+" *"
    xlist_label.append(cat)

plt.xticks(ticks=range(0,25),labels=xlist_label)

    
# plt.show()
plt.savefig('../Fear_speech_results/empath.pdf',bbox_inches='tight',dpi=400)

In [ ]:
# fear_speech_df=annotated_df[annotated_df['one_fear_speech']==1]
# non_fear_speech_df=annotated_df[annotated_df['one_fear_speech']==0]

# test_heldout_fs=fear_speech_df.sample(500,random_state=2020)
# test_heldout_nfs=non_fear_speech_df.sample(500,random_state=2020)

# gold_train_fs=fear_speech_df.drop(test_heldout_fs.index)
# gold_train_nfs=non_fear_speech_df.drop(test_heldout_nfs.index)

# gold_train=pd.concat([gold_train_fs,gold_train_nfs])
# test_heldout=pd.concat([test_heldout_fs,test_heldout_nfs])
 
# gold_train.to_csv(parent_path+'gold_labels.csv',index=False)
# test_heldout.to_csv(parent_path+'test_heldout.csv',index=False)

In [ ]:
import matplotlib
matplotlib.rcParams['figure.figsize'] = (15, 6)
# font = {
#     'weight' : 'normal',
#     'size'   : 15}
# matplotlib.rc('font', **font)
#data_timeline.plot()
sns.set(context='paper',style='white',font_scale=1.0)
window=7
ax = sns.lineplot(x="length", y="number of docs",hue="label",style="label",data=df_token_length,hue_order=dict_map.values(),markers=True,dashes=False,estimator=np.mean)
plt.xlabel('length of words')
plt.ylabel('number of words')
plt.legend()
#plt.yscale('log')
#plt.savefig('Results/Whatsapp_usage_of_keywords.jpg',bbox_inches='tight',dpi=400)
plt.show() 

In [ ]:
edges={}
emoji_dict={}
emoji_dict_count={}
emoji_dict_reverse={}
window=5


count=0
for index,row in tqdm_notebook(annotated_df[annotated_df['one_fear_speech']==1].iterrows(),total=len(annotated_df[annotated_df['one_fear_speech']==1])):
    emojis_with_index=extract_emojis_index(row['message_text'])
    
    
    for ele in emojis_with_index:
        try:
            emoji_dict_count[ele[1]]+=1
        except KeyError:
            emoji_dict_count[ele[1]]=1
    
    
    for i in range(len(emojis_with_index)):
        ele1=emojis_with_index[i]
        for j in range(i,len(emojis_with_index)):
            ele2=emojis_with_index[j]
            
            try:
                temp1=emoji_dict[ele1[1]]
            except:
                count+=1
                emoji_dict[ele1[1]]=count
                emoji_dict_reverse[count]=ele1[1]
                temp1=count
            
            try:
                temp2=emoji_dict[ele2[1]]
            except:
                count+=1
                emoji_dict[ele2[1]]=count
                emoji_dict_reverse[count]=ele2[1]
                temp2=count
            
            if(temp1<temp2):
                key_adj=str(temp1)+'--'+str(temp2)
            elif(temp2<temp1):
                key_adj=str(temp2)+'--'+str(temp1)
            else:  
                continue
            try:
#                 edges[key_adj][0]+=abs(ele1[0]-ele2[0])
#                 edges[key_adj][1]+=1
                if(abs(ele1[0]-ele2[0]) <window):
                    edges[key_adj]+=1


            except KeyError:
#                 edges[key_adj]=[abs(ele1[0]-ele2[0]),1]
                 if(abs(ele1[0]-ele2[0])<window):
                    
                    edges[key_adj]=1
            

In [ ]:
edge_list=[]

for key in edges.keys():
    ele1=int(key.split('--')[0])
    ele2=int(key.split('--')[1])
    if(emoji_dict_count[inv_map[ele1]]<10 or emoji_dict_count[inv_map[ele2]]<10 or inv_map[ele1] in emoji_stop or inv_map[ele2] in emoji_stop):
        continue
        
    avg_distance= edges[key]/(emoji_dict_count[inv_map[ele1]]*emoji_dict_count[inv_map[ele2]])
    edge_list.append([ele1,ele2,avg_distance])

In [ ]:
import json
with open("Networks/emoji_dict.json", 'w') as fp:
    json.dump(emoji_dict, fp,ensure_ascii=False)

In [ ]:
G = nx.Graph()
G.add_weighted_edges_from(edge_list)

In [ ]:
nx.write_weighted_edgelist(G, "Networks/network_emoji_98.edgelist.gz")

### Load precomputed emoji network

In [3]:

import json
with open("Networks/emoji_dict.json", 'r') as fp:
    emoji_dict=json.load(fp)
emoji_dict_reverse = {v: k for k, v in emoji_dict.items()}

G=nx.read_weighted_edgelist("Networks/network_emoji_98.edgelist.gz")
    

In [ ]:
import community as community_louvain
import networkx as nx
partion = community_louvain.best_partition(G)

In [ ]:
partition_emoji={}
for key in partion:
    emoji=emoji_dict_reverse[key]
    try:
        partition_emoji[partion[key]].append(emoji)
    except KeyError:
        partition_emoji[partion[key]]=[emoji]

In [ ]:
for key in partition_emoji:
    print(partition_emoji[key])

In [ ]:
temp=latex_emoji_communities(partition_emoji)
with open("Output.txt", "w") as text_file:
    print(temp, file=text_file)

#### Topic analysis



In [ ]:
from gensim.models.ldamodel import LdaModel
import gensim


def handler_funtion(data):
    processed_words=list(data['tokenized'])
    dictionary = gensim.corpora.Dictionary(processed_words)
    dictionary.filter_extremes(no_below=3, no_above=0.5, keep_n=50000)
    list_docs=[]
    for index,row in tqdm_notebook(data.iterrows(),total=len(data)):
        list_docs.append(dictionary.doc2bow(row['tokenized']))
    idxtoken={k:v for v,k in dictionary.token2id.items()}
    return dictionary,idxtoken,list_docs

def get_topic(time_filtered_data,num_topics=10):
    '''make sure to have the time as a tuple (year,month,day,hr,min,sec) and the data is a dataframe'''
    '''to channge the model parameters change it in 09_topicmodeling.ipynb'''
    print(len(time_filtered_data))    
    params={'remove_numbers':True,'remove_emoji':False,'remove_stop_words':True,'tokenize':True}
    token_list=[preprocess_sent(ele,params) for ele in tqdm_notebook(list(time_filtered_data['message_text']),total=len(time_filtered_data))]    
    time_filtered_data['tokenized']=token_list
    dictionary,idxtoken,list_docs= handler_funtion(time_filtered_data)
    time_filtered_data['topic']=-1
    
    #lda=LatentDirichletAllocation(n_components=num_topics,n_jobs=-1,max_iter=20,evaluate_every=1)
    lda = LdaModel(list_docs, id2word=idxtoken, num_topics=num_topics,chunksize=100,passes=20)
    #lda.fit(dense_vector)
    topic_list=[]
    lda_topics=lda.show_topics(num_topics=num_topics,formatted = False,num_words=15)

    for index, topic in enumerate(lda_topics):
        topic=topic[1]
        topic_list.append([ele[0] for ele in topic])
    for index,row in tqdm_notebook(time_filtered_data.iterrows(),total=len(time_filtered_data)):
        #topic_vector=lda.transform(dense_vector[i].reshape(1,-1))
        #print(row['tokenized'])
        try:
            vector=lda[dictionary.doc2bow(row['tokenized'])]
            vector=[ele[1] for ele in vector]
            time_filtered_data.at[index,'topic']=np.argmax(vector)
        except:
            time_filtered_data.at[index,'topic']=0
    return time_filtered_data,lda_topics

In [ ]:
time_filtered_data,topic_list=get_topic(annotated_df[annotated_df['one_fear_speech']==1],num_topics=5)

In [ ]:
lexicon_path='../Data/Important_lexicon/'
########################################
def get_lexicon(type1,path):
    lexicon=[]
    with open(path+type1+'_keywords_complete.txt', 'r') as f:
        temp=f.read().splitlines()
    for word in temp:
        lexicon.append(word)
    return lexicon

muslim_lexicon=get_lexicon('muslim',lexicon_path)
hindu_lexicon=get_lexicon('hindu',lexicon_path)

In [14]:
fear_speech_unique=annotated_df[annotated_df['one_fear_speech']==1]

In [16]:
params={'remove_numbers':True,'remove_emoji':False,'remove_stop_words':True,'tokenize':True}


list_preprocessed=[]
for ele in tqdm(fear_speech_unique['message_text']):
    temp=preprocess_sent(ele,params)
    temp_new=[]
    for word in temp:
        if(word not in ['मुसलमान','मुसलमानों','मुस्लिम']+emoji_stop):
            temp_new.append(word) 
    list_preprocessed.append(temp_new)
fear_speech_unique['preprocessed']=list_preprocessed

100%|██████████| 1142/1142 [00:22<00:00, 50.26it/s]
/home/punyajoy/.conda/envs/punyajoy_gpu/lib/python3.7/site-packages/ipykernel_launcher.py:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if sys.path[0] == '':


In [17]:
fear_speech_unique['preprocessed'][0:5]

0     [प्रशासक, समिति, ✊, 🚩, 😎, 🚩, आंतकवादी, संगठनों...
2     [इस्लाम, धर्म, मानसिक, रोग, शी, जिनपिंग, चीनी,...
5     [सर्फ़_एक्सेलकपड़ों, हिंदुओं, धो, त्योहारों, विश...
8     [🎭, 👉, वायनाड, बारे, अच्छे, जान, ले, राहुल, गा...
10    [प्रशासक, समिति, ✊, 🚩, पोस्ट, आतंकवाद, इलाज, आ...
Name: preprocessed, dtype: object

In [18]:
import gensim

data_words = fear_speech_unique.preprocessed.values.tolist()

bigram = gensim.models.Phrases(data_words, min_count=2, threshold=3) # higher threshold fewer phrases.
trigram = gensim.models.Phrases(bigram[data_words], threshold=3)  

# Faster way to get a sentence clubbed as a trigram/bigram
bigram_mod = gensim.models.phrases.Phraser(bigram)
trigram_mod = gensim.models.phrases.Phraser(trigram)

In [19]:
def make_bigrams(texts):
    return [bigram_mod[doc] for doc in texts]

def make_trigrams(texts):
    return [trigram_mod[bigram_mod[doc]] for doc in texts]

data_words_bigrams = make_bigrams(data_words)

In [20]:
import gensim.corpora as corpora


In [21]:
# Create Dictionary
id2word = corpora.Dictionary(data_words_bigrams)
id2word.filter_extremes(no_below=1, no_above=0.1)

# Create Corpus
texts = data_words_bigrams

# Term Document Frequency
corpus = [id2word.doc2bow(text) for text in texts]

# View
print(corpus[:1][0][:30])

[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1), (12, 1), (13, 1), (14, 1), (15, 1), (16, 1), (17, 1), (18, 1), (19, 1), (20, 1), (21, 1), (22, 1), (23, 1), (24, 1), (25, 1), (26, 1), (27, 1), (28, 1), (29, 1)]


In [ ]:
from gensim.models import CoherenceModel

import pprint

# Build LDA model
coherence_list=[]
for numtopics in tqdm_notebook(range(2,40)):
        lda_model = gensim.models.LdaMulticore(corpus=corpus,
                                               id2word=id2word,
                                               num_topics=numtopics, 
                                               random_state=2020,
                                               chunksize=100,
                                               passes=20,
                                               per_word_topics=True)

        coherence_model_lda = CoherenceModel(model=lda_model, texts=data_words_bigrams, dictionary=id2word, coherence='c_v')
        coherence_lda = coherence_model_lda.get_coherence()
        coherence_list.append(coherence_lda)
        #pprint()
        with open("file_out.txt", "a") as fout:
                fout.write("Topic"+str(numtopics)+'\n')
                fout.write(pprint.pformat(lda_model.print_topics(num_words=20)))
        

In [ ]:
plt.plot(coherence_list)

In [ ]:
lda_model = gensim.models.LdaMulticore(corpus=corpus,
                                               id2word=id2word,
                                               num_topics=10, 
                                               random_state=2020,
                                               chunksize=100,
                                               passes=20,
                                               per_word_topics=True)



In [ ]:
coherence_lda

In [ ]:
from gensim.test.utils import datapath
# Save model to disk.
temp_file = datapath("lda_model_10")
lda_model.save(temp_file)

### Load precomputed lda model


In [9]:
import gensim
from gensim.test.utils import datapath
# Save model to disk.
temp_file = datapath("lda_model_10")

lda_model =  gensim.models.LdaMulticore.load(temp_file)
# coherence_model_lda = CoherenceModel(model=lda_model, texts=data_words_bigrams, dictionary=id2word, coherence='c_v')
# coherence_lda = coherence_model_lda.get_coherence()


In [10]:
#### Topics to table
from gtrans import translate_text, translate_html
from utils.visualisation import *
def add_topics_table(lda_model):
    str1='\\begin{table*}[!tbh]\n\centering\n\caption{List of topics discussed in fear speech}\n\\begin{tabular}{p{13cm}l}\n \\textbf{Words} & \\textbf{Topic}\\\\'
    for i in range(lda_model.num_topics):
        topic_words=lda_model.show_topic(i,topn=25)
        for word in topic_words:
            word_english=""
            for word_ele in word[0].split('_'):
                print(word_ele)
                if word_ele in emoji.UNICODE_EMOJI:
                    print("hello")
                    word_english+=emoji_string(word_ele)+"\_"
                else:         
                    word_english_ele=translate_text(word_ele,'hi', 'en')
                    word_english+=word_english_ele.rstrip().lower()+"\_"
            str1+=word_english[:-2]+', '
        str1=str1[:-2]+"& Dummy inference \\\\\\hline\n"
        
    str1+="\end{tabular}\n\label{tab:topics_fear_speech}\n\end{table*}"


    return str1

In [ ]:
str1=""
str1=add_topics_table(lda_model)

In [ ]:
with open("Output_topics.txt", "w") as text_file:
    print(str1, file=text_file)

In [22]:


topic_tuples=[]

for index,row in fear_speech_unique.iterrows():
    vector_final = np.zeros((10,))
    vector,_,_=lda_model[id2word.doc2bow(row['preprocessed'])]
    for ele in vector:
        vector_final[ele[0]]=ele[1]
        
    topic_number=np.argmax(vector_final)
    topic_tuples.append(list(vector_final)+[topic_number])
    
    
column_names= ['Topic'+str(i) for i in range(0,10)]+['topic_number']
df_topics=pd.DataFrame(topic_tuples,columns=column_names)



In [24]:
fear_speech_unique_with_topics=pd.concat([df_topics.reset_index(),fear_speech_unique.reset_index()],axis=1)

In [38]:

for i in range(0,10):
    fear_speech_unique_with_topics=fear_speech_unique_with_topics.sort_values('Topic'+str(i),ascending=False)
    fear_speech_unique_with_topics[0:5][['Topic'+str(i),'message_text']].to_csv('Topics/Topic'+str(i)+'_top5.csv',index=False)

In [36]:
fear_speech_unique_with_topics.sort_values('Topic1',ascending=False)

index    Topic0    Topic1    Topic2    Topic3    Topic4    Topic5  \
665     665  0.000000  0.995277  0.000000  0.000000  0.000000  0.000000   
192     192  0.000000  0.993511  0.000000  0.000000  0.000000  0.000000   
209     209  0.000000  0.977461  0.000000  0.000000  0.000000  0.000000   
148     148  0.000000  0.977309  0.014964  0.000000  0.000000  0.000000   
1021   1021  0.000000  0.969908  0.000000  0.000000  0.000000  0.000000   
...     ...       ...       ...       ...       ...       ...       ...   
440     440  0.000000  0.000000  0.000000  0.976404  0.019586  0.000000   
441     441  0.031512  0.000000  0.000000  0.043005  0.026924  0.000000   
443     443  0.000000  0.000000  0.000000  0.656955  0.000000  0.053702   
444     444  0.000000  0.000000  0.000000  0.186082  0.419695  0.000000   
1141   1141  0.000000  0.000000  0.000000  0.845679  0.000000  0.044334   

        Topic6    Topic7  Topic8  ...  preds  \
665   0.000000  0.000000     0.0  ...    NaN   
192   0.000000  0.000000     0.0  ...    NaN   
209   0.000000  0.000000     0.0  ...    NaN   
148   0.000000  0.000000     0.0  ...    1.0   
1021  0.000000  0.000000     0.0  ...    1.0   
...        ...       ...     ...  ...    ...   
440   0.000000  0.000000     0.0  ...    NaN   
441   0.048592  0.066452     0.0  ...    NaN   
443   0.000000  0.093186     0.0  ...    NaN   
444   0.000000  0.293439     0.0  ...    NaN   
1141  0.098419  0.000000     0.0  ...    1.0   

                                               repeated     timestamp  \
665                                         [2563961.0]           NaN   
192   [2047774.0, 2290596.0, 6203429.0, 3813804.0, 8...  1.546662e+12   
209   [2437635.0, 4816230.0, 4810637.0, 4809782.0, 4...  1.549090e+12   
148   [1473953.0, 4274467.0, 2904326.0, 1473735.0, 5...  1.559652e+12   
1021                                        [4107484.0]  1.563165e+12   
...                                                 ...           ...   
440                                         [4081951.0]  1.565141e+12   
441                                         [4086870.0]  1.565344e+12   
443                                         [4372960.0]  1.550289e+12   
444                                         [4376509.0]  1.550329e+12   
1141                                        [6269592.0]  1.562183e+12   

                                              tokenized  \
665                                                 NaN   
192   [eye, opening, message, to, all, scroll, down,...   
209   [ईमान, का, नाम, मुसलमान, ?, यह, मात्र, हिन्दू,...   
148   [प्रशासक, समिति, raised_fist, triangular_flag,...   
1021  [bollywood, actor, ajaz, khan, spitting, venom...   
...                                                 ...   
440   [collision, collision, collision, collision, c...   
441   [सेवा, में, श्री, नरेंद्र, मोदी, जी, प्रधानमंत...   
443   [face_screaming_in_fear, सेना, की, शहादत, को, ...   
444   [triangular_flag, sun_with_face, धर्म, संस्थाप...   
1141  [फिर, कहते, हैं, #, राममन्दिर, नहीं, बना, ____...   

                                             translated  \
665   لماذا تزوج النبي محمد عدة  زوجات 3⃣ ترجمة اللغ...   
192   Eye opening message to all. Scroll down for mi...   
209   Name of faith is Muslim? It is just a proverb ...   
148   * Administrator 🚩  ✊  committee * * 👇 👇   👇  V...   
1021  Bollywood actor Ajaz Khan spitting venom or ra...   
...                                                 ...   
440   17 💥 💥 💥 💥 💥  💥   💥   💥   💥   💥  💥  Only 17% o...   
441   In service, 1. Shri Narendra Modi, Prime Minis...   
443   * 😱  24 hours of martyrdom of the army was not...   
444   * 🚩 🌞   Religion Establishment ⛳  🚩  🌞  * * Ha...   
1141  Then it says #Ramandir is not made ___________...   

                                             unique_ids  \
665                                                 NaN   
192   [d2af2418-c3a2-4006-980c-9209cd12f47e, 5b0374a...   
209   [7b40d44d-5f4a-45d8-94f8-fc86870298e6, 6332d2a... 

In [ ]:
matplotlib.rcParams['figure.figsize'] = (5, 5)

temp_dict={}
for ele in list(df_topics['topic_number']):
    try:
        temp_dict[ele]+=1
    except:
        temp_dict[ele]=1
    



sorted_tuple = sorted(temp_dict.items(), key=lambda x: x[1],reverse=True) 
df=pd.DataFrame(sorted_tuple,columns=['Topic','Number of posts'])
sns.set(context='paper',style='white',font_scale=1.5)

#df.columns= ['Stance of the messages','Number of unique messages (out of top 100)']
g = sns.barplot(x=df.columns[0],y=df.columns[1],data=df,order=[ele[0] for ele in sorted_tuple])
plt.savefig('../Fear_speech_results/topic_fear_speech.pdf',bbox_inches='tight',dpi=400)

In [ ]:
fear_speech_unique.columns

In [ ]:
df_topics

###  use of postags

In [ ]:
import stanza

In [ ]:
stanza.download('hi') # download English model
nlp = stanza.Pipeline('en',use_gpu=False) # initialize English neural pipeline
doc = nlp("Barack Obama was born in Hawaii.He was a cool kid") # run annotation over a sentence

In [ ]:
annotated_df.columns

In [ ]:
tuple_dict={}
tuple_list_final={}


nlp_hindi=nlp = stanza.Pipeline('hi',use_gpu=False) # initialize English neural pipeline
nlp_english=nlp = stanza.Pipeline('en',use_gpu=False) # initialize English neural pipeline




for index,row in tqdm_notebook(annotated_df[annotated_df['one_fear_speech']==1].iterrows(),total=len(annotated_df[annotated_df['one_fear_speech']==1])):
#     nlp = stanza.Pipeline(row['language'],use_gpu=False) # initialize English neural pipeline
    if(row['language']!='en'):
        nlp=nlp_hindi
    else:
        nlp=nlp_english
    params={'remove_numbers':True,'remove_emoji':True,'remove_stop_words':True,'tokenize':False}
    preprocess_sent_temp=preprocess_sent(row['message_text'],params)
    doc = nlp(preprocess_sent_temp) 
    temp = {}
    tuple_list_final[index]=doc.to_dict()
    for element in doc.to_dict():
        for ele in element:
            if(ele['upos'] in ['PROPN']):
                try:
                    temp[ele['upos']]+=1
                except KeyError:
                    temp[ele['upos']]=1
    tuple_dict[index]=temp

In [ ]:
import pickle


with open(parent_path+'stanza_run.pickle', 'wb') as handle:
    pickle.dump(tuple_list_final, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [ ]:
import pandas as pd

object = pd.read_pickle(parent_path+'stanza_run.pickle')

In [ ]:
tuple_dict={}

for key in tuple_list_final.keys():
    doc=tuple_list_final[key]
    temp = {}
    for element in doc:
        for ele in element:
            if(ele['upos'] in ['NOUN']):
                try:
                    try:
                        print(int(ele['text']))
                    except ValueError:
                        temp[ele['text']]+=1
                except KeyError:
                    try:
                        print(int(ele['text']))
                    except ValueError:
                        temp[ele['text']]=1
                    
    tuple_dict[key]=temp



In [ ]:
tuple_list_corpus=[]
for key in tuple_dict:
    for ele in tuple_dict[key]:
        
        tuple_list_corpus.append([key,ele,tuple_dict[key][ele]])

In [ ]:
df=pd.DataFrame(tuple_list_corpus,columns=['label','term','n'])

In [ ]:
df=df.set_index(['label'],drop=True)

df

In [ ]:
from textnets import Corpus, Textnet

In [ ]:
tn = Textnet(df, min_docs=5)

In [ ]:
tn.top_closeness(100)

In [ ]:
import shifterator as sh

def dict_freq(df):
    dict_fear_speech={}
    dict_normal={}
    for index,row in tqdm_notebook(df.iterrows(),total=len(df)):
        params={'remove_numbers':True,'remove_emoji':True,'remove_stop_words':True,'tokenize':True}
        preprocess_sent_temp=preprocess_sent(row['translated'],params)
        if(row['one_fear_speech']==1):
            for ele in preprocess_sent_temp:
                try:
                    dict_fear_speech[ele]+=1
                except KeyError:
                    dict_fear_speech[ele]=1
        if(row['one_fear_speech']==0):
            for ele in preprocess_sent_temp:
                try:
                    dict_normal[ele]+=1
                except KeyError:
                    dict_normal[ele]=1
    return dict_fear_speech, dict_normal
    
dict_fear_speech, dict_normal=dict_freq(annotated_df)

In [ ]:
proportion_shift = sh.EntropyShift(type2freq_1=dict_fear_speech,
                                      type2freq_2=dict_normal,base=2)
proportion_shift.get_shift_graph(system_names = ['Fear speech', 'Non Fear speech'],
                                 title='Entropy shift of Fear speech posts',top_n=50)

In [ ]:
from googlesearch import search,get_tbs

In [ ]:
i=10
print(fear_speech_unique.iloc[i]['translated'])
for url in search(fear_speech_unique.iloc[i]['translated'][0:4000], stop=100):
    print(url)

### Are these toxic


In [39]:
from transformers import AutoTokenizer, AutoModelForSequenceClassification
tokenizer = AutoTokenizer.from_pretrained("jpcorb20/toxic-detector-distilroberta")
model = AutoModelForSequenceClassification.from_pretrained("jpcorb20/toxic-detector-distilroberta")


/home/punyajoy/.conda/envs/punyajoy_gpu/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/punyajoy/.conda/envs/punyajoy_gpu/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/punyajoy/.conda/envs/punyajoy_gpu/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/punyajoy/.conda/envs/puny

I1015 08:02:29.165015 140594723530560 filelock.py:318] Lock 140585965911232 released on /home/punyajoy/.cache/torch/transformers/1dd3446776e748386dd6029f68ffbdf37ef7bca64fe813bd8b4deff8f04bef46.510a1bb1567601a945a39634bc2d9f947940f9f1fac21299c6178c5972362762.lock


I1015 08:02:30.282759 140594723530560 filelock.py:274] Lock 140585965910896 acquired on /home/punyajoy/.cache/torch/transformers/c60729ac97c0b503eaa950629ed8871de6a2fb9b7809e940c2bcdbc447c46829.6a4061e8fc00057d21d80413635a86fdcf55b6e7594ad9e25257d2f99a02f4be.lock


I1015 08:02:33.160276 140594723530560 filelock.py:318] Lock 140585965910896 released on /home/punyajoy/.cache/torch/transformers/c60729ac97c0b503eaa950629ed8871de6a2fb9b7809e940c2bcdbc447c46829.6a4061e8fc00057d21d80413635a86fdcf55b6e7594ad9e25257d2f99a02f4be.lock


I1015 08:02:34.255779 140594723530560 filelock.py:274] Lock 140588938655336 acquired on /home/punyajoy/.cache/torch/transformers/848560d8a4b6ade87eabfbe8c3c9c6fbdb8b66089606f19ea5ea6d7ff1e1f7b9.b5db7aa9098dc1cd7639d40444ec17d44bc31efce1a97b3a8b5dc3910380920f.lock


I1015 08:02:36.946871 140594723530560 filelock.py:318] Lock 140588938655336 released on /home/punyajoy/.cache/torch/transformers/848560d8a4b6ade87eabfbe8c3c9c6fbdb8b66089606f19ea5ea6d7ff1e1f7b9.b5db7aa9098dc1cd7639d40444ec17d44bc31efce1a97b3a8b5dc3910380920f.lock


I1015 08:02:39.239092 140594723530560 filelock.py:274] Lock 140588938655336 acquired on /home/punyajoy/.cache/torch/transformers/7f557bae202bf3fdf86d6ff93093538e67e88fa89830c1eb66d7909fb72d719a.6e217123a3ada61145de1f20b1443a1ec9aac93492a4bd1ce6a695935f0fd97a.lock


I1015 08:02:40.446129 140594723530560 filelock.py:318] Lock 140588938655336 released on /home/punyajoy/.cache/torch/transformers/7f557bae202bf3fdf86d6ff93093538e67e88fa89830c1eb66d7909fb72d719a.6e217123a3ada61145de1f20b1443a1ec9aac93492a4bd1ce6a695935f0fd97a.lock


I1015 08:02:41.645731 140594723530560 filelock.py:274] Lock 140588938655336 acquired on /home/punyajoy/.cache/torch/transformers/0f1c839e55534d2497ebb75412249d42431bd33cb147788dd880d8fd414938a4.11f57497ee659e26f830788489816dbcb678d91ae48c06c50c9dc0e4438ec05b.lock


I1015 08:02:42.772930 140594723530560 filelock.py:318] Lock 140588938655336 released on /home/punyajoy/.cache/torch/transformers/0f1c839e55534d2497ebb75412249d42431bd33cb147788dd880d8fd414938a4.11f57497ee659e26f830788489816dbcb678d91ae48c06c50c9dc0e4438ec05b.lock


I1015 08:02:46.298244 140594723530560 filelock.py:274] Lock 140585850312744 acquired on /home/punyajoy/.cache/torch/transformers/35a3bcfebdbbedceb80cb1a7791a8c28e1a612e4b849e5f69c6ec49458b9fde2.3308da0365a2432af82617d72aa0cc33b6f58335301b2cb038c146c5287a6255.lock


I1015 08:03:12.281492 140594723530560 filelock.py:318] Lock 140585850312744 released on /home/punyajoy/.cache/torch/transformers/35a3bcfebdbbedceb80cb1a7791a8c28e1a612e4b849e5f69c6ec49458b9fde2.3308da0365a2432af82617d72aa0cc33b6f58335301b2cb038c146c5287a6255.lock


In [56]:
list_model_confidence=[]
for index,row in tqdm_notebook(fear_speech_unique.iterrows(), total=len(fear_speech_unique)):
    tokens_pt2 = tokenizer.encode_plus(row["translated"][0:100], return_tensors="pt")
    outputs2 = model(**tokens_pt2)
    from torch import nn
    m = nn.Softmax(dim=1)
    output = m(outputs2[0])
    list_model_confidence.append(output.detach().numpy()[0])

/home/punyajoy/.conda/envs/punyajoy_gpu/lib/python3.7/site-packages/ipykernel_launcher.py:2: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  


In [60]:
list_model_confidence

[array([0.8367642 , 0.00143447, 0.00487477, 0.00250229, 0.03076649,
        0.12365768], dtype=float32),
 array([0.64753705, 0.01591771, 0.02043707, 0.01866737, 0.07877088,
        0.21866998], dtype=float32),
 array([0.65347165, 0.02732602, 0.13166142, 0.02264035, 0.12232511,
        0.04257545], dtype=float32),
 array([0.78992385, 0.01274505, 0.08173247, 0.01352303, 0.07824812,
        0.02382751], dtype=float32),
 array([0.5554631 , 0.04625457, 0.1560166 , 0.0374085 , 0.14176701,
        0.06309029], dtype=float32),
 array([0.71612275, 0.02255998, 0.10396978, 0.02338681, 0.08987654,
        0.0440842 ], dtype=float32),
 array([0.7093165 , 0.02395785, 0.0867808 , 0.03188404, 0.11006359,
        0.03799726], dtype=float32),
 array([0.5399175 , 0.01847635, 0.02477283, 0.02562848, 0.04964042,
        0.34156445], dtype=float32),
 array([0.7541945 , 0.0146461 , 0.08577023, 0.01633469, 0.09575631,
        0.03329824], dtype=float32),
 array([0.5371984 , 0.00459101, 0.00974383, 0.00552301,

In [64]:
from perspective import Perspective 


p = Perspective("AIzaSyAUYdcELBp_FIPyiCQ6UfDEDIfDJDiShLE") 
comment = p.score("This is a comment", tests=["TOXICITY"]) 

print("Toxicity score: " + comment["TOXICITY"].score) 

ModuleNotFoundError: No module named 'perspective'